public enum EventType {
    BOOK_DISCUSSION,
    AUTHOR_VISIT,
    MOVIE_SCREENING,
    BOOK_SALE,
    CHILDREN_STORY_TIME,
    CHILDREN_WORKSHOP,
    ELEMENTARY_READING_GROUP,
    SCHOOL_FIELD_TRIP,
    SUMMER_DAY_CAMP
}
